### ISSUE TITLE
Find smallest sum in an array?

### ISSUE THREAD

**Issue by rishabhgarg25699** [sahilbansal17/Competitive_Coding#161]
We are given a sequence a1, a2, ..., aN. We have to find the smallest possible value of ai + aj ,
 where 1 ≤ i < j ≤ N. We have also given the size of array.

Exanple   No. of elements 5
                     {3,2,5,7,1)
Ans       3
HINT (2+1)

**Comment by rishabhgarg25699** [comment]
I have uploaded the answer of this question on algorithms and Computational-Geometry folder.
Please review it.

**Comment by ramitsawhney27** [comment]
Please wait for mentors to approve issues before solving them. 
A few points:
1. This problem is fairly simple and we would not award any points for this.
2. You should send a PR to the repo rather along with uploading it to your local copy.
3. Why is this in the computational geometry folder?
4. This can be solved in a time complexity better than O(n^2).
